project:
  type: website
  
  preview: 
    port: 5999

website:
  title: "kaitakeranges.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
        icon: house-door
      - text: "Status"
        href: status.qmd
        icon: file-bar-graph
      - text: "Trap Line Summary"
        href: trapline.qmd
        icon: table
      - text: "Trap Line Status"
        href: trapstatus.qmd
        icon: file-bar-graph
  page-footer: "An R Quarto Website" <br> 
                "Data sourced from trap.nz"

format:
  html:
    theme:
      - styles.scss
      - cosmo
    toc: true
    page-layout: full
