project:
  type: website
  
  preview: 
    port: 5999

website:
  title: "Kaitake Ranges Conservation Trust"
  navbar:
    left:
      - text: "Catch Summary"
        href: catchsummary.qmd
        icon: file-bar-graph
      - text: "Trap Summary"
        href: trapsummary.qmd
        icon: table
      - text: "Trap Line Status"
        href: traplinestatus.qmd
        icon: file-bar-graph
  page-footer:
    An R Quarto Website <br>
    Trap data sourced from <a href="https://trap.nz" target="_blank">trap.nz</a>
    <div class="source-link-container"><img src="images/GitHub-Mark-32px.png" alt="github logo" /> see <a href="https://github.com/kaitakeranges/kaitakeranges.github.io" target="_blank" >repository</a> on GitHub</div>
format:
  html:
    theme:
      - styles.scss
      - cosmo
    toc: true
    page-layout: full
