project:
  type: website

website:
  title: "kaitakeranges.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-door
      - about.qmd
    page-footer: "An R Quarto Website"

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    page-layout: full

editor: visual

