project:
  type: website
  
  preview: 
    port: 5999

website:
  title: "kaitakeranges.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
        icon: house-door
  page-footer: "An R Quarto Website"

format:
  html:
    theme:
      - styles.scss
      - cosmo
    toc: true
    page-layout: full
