name: Scheduled ETL

on:
  schedule:
    - cron: "20 22 * * *"

jobs:
  import-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      
      - name: Run ETL script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
        run: Rscript -e 'source("etl.R")'
      
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
          
      - name: Add Timestamp and force push
        run: |
          echo "Last updated: $(date)" > last_updated.txt
          git add last_updated.txt
          git commit -m 'Update timestamp'
          git push origin main || echo "No changes to commit"